# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels: [ ]     # Do not add default "dependency" label

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels: [ ]     # Do not add default "dependency" label
    open-pull-requests-limit: 20

  - package-ecosystem: "nuget"
    directory: "/analyzers"
    schedule:
      interval: "daily"
    labels: [ ]     # Do not add default "dependency" label
    open-pull-requests-limit: 20
