blank_issues_enabled: false

contact_links:

  - name: Report problems with raised issues.
    url: https://community.sonarsource.com/tags/c/clean-code/fp/7/dotnet
    about: Community Forum - Report False-positive / False-negative, or AD0001

  - name: Request support or report a bug using SonarLint.
    url: https://community.sonarsource.com/c/sl/11
    about: Community Forum - SonarLint.

  - name: Request support or report a bug using SonarCloud.
    url: https://community.sonarsource.com/c/sc/9
    about: Community Forum - SonarCloud.

  - name: Request support or report a bug using SonarQube.
    url: https://community.sonarsource.com/c/sq/10
    about: Community Forum - SonarQube

  - name: Suggest new feature
    url: https://community.sonarsource.com/c/clean-code/rules/13
    about: Community Forum - Clean Code / New rules
