name: Create Milestone

on:
  milestone:
    types: ["created"]

jobs:
  CreateRspecIssue_job:
    name: Create RSPEC Issue
    runs-on: ubuntu-latest
    steps:
      - uses: sonarsource/gh-action-lt-backlog/CreateRspecIssue@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          column-id: 4971951  # Kanban "To Do" column
          body: "cc @denis-troller"
