name: Start Progress

on:
  project_card:
    types: ["moved"]

jobs:
  AssignCardToSender_job:
    runs-on: ubuntu-latest
    if: |
        github.event.changes.column_id.from == 4971951
        && github.event.project_card.content_url != null
    steps:
      - uses: sonarsource/gh-action-lt-backlog/AssignCardToSender@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
