name: Start Progress

on:
  project_card:
    types: ["moved"]

jobs:
  assign_to_self:
    runs-on: ubuntu-latest
    if: |
        github.event.changes.column_id.from == 4971951
        && github.event.project_card.column_id == 4971952
        && github.event.project_card.content_url != null
    steps:
      # https://github.com/actions/github-script
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            //
            async function addAssignee(issue, login) {
                console.log("Assigning to: " + login);
                await github.issues.addAssignees({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    assignees: [login]
                });
            }
            //
            const url = context.payload.project_card.content_url;
            console.log("Processing " + url);
            var issue = (await github.request(url)).data;
            if(!issue.assignee){
                addAssignee(issue, context.payload.sender.login);
            }
            console.log(`Done`);


